spring:
 jpa:
  database: POSTGRESQL
 datasource:
   driverClassName: org.postgresql.Driver
   url: jdbc:postgresql://localhost:5432/shoppinglist
   username: ${psql.user}
   password: ${psql.password}