# h2 http://localhost:8080/h2-console
spring:
 datasource:
  driver-class-name: org.h2.Driver
  url: jdbc:h2:mem:shoppingList
  username: sa
  password: shoppinglistpass

 h2:
  console:
   enabled: true
  
debug: true